### PR TITLE
Migrate to python3 super() call style.

### PR DESCRIPTION
**Pull request by ambuc**
This enables a future change which performs recursive module reloading, but it isn't possible to perform arbitrary-order reloading with the python2-style super(Foo, self) call style.

This change makes possible https://github.com/BlackFoundryCom/robo-cjk/pull/20.

### CODE REVIEW

**Comment by GaetanBaehr** [comment]
Hello, I'm not used to merging PR, how can I be sure to merge this pull request on the dev branch ? (The dev branch is now up to date)

**Comment by ambuc** [comment]
I want to follow whatever the standard practice is for this repo. Should I have taken this PR against `dev` instead?

If there's no standard practice, then we could either:

1) submit this PR into `master`, then cherry-pick the commit into `dev`, or

2) "clean up" `master` and `dev` so that one is clearly ahead of the other. Then we can take out PRs against `master` and rebase from master back into the `dev` branch. At that point, the dev branch doesn't really need to exist; I would just take out temporary feature branches for each new feature.

I think (1) is the most expedient, but (2) is probably the right solution long-term. What do you think?

**Comment by justvanrossum** [comment]
FWIW I agree with (2): it is much much easier to manage short lived feature branches than to permanently use a dev branch. And use PRs for every non-trivial change, even if only one person is involved.

**Comment by GaetanBaehr** [comment]
Sorry for the delay, I merge now your pull requests

**Pull request merged**
